plugins {
    id 'com.android.application'
}

android {
    namespace 'com.guru.handwritingkeyboard'
    compileSdk 35

    defaultConfig {
        applicationId 'com.guru.handwritingkeyboard'
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName '2.0'
    }
}

dependencies {
    implementation 'androidx.core:core:1.15.0'
}
